<a href="https://colab.research.google.com/github/jhariyakamlesh2/Data-Analyst/blob/master/Numpy_in_gen_ai_and_agentic_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Arrays
arr = np.array([1, 2, 3, 4, 5])
print("Array:" , arr)

Array: [1 2 3 4 5]


In [ ]:
# Random numbers of AI
rand = np.random.rand(5) # Gaussian Distribution
print("Random Vector:" , rand)

Random Vector: [0.62684839 0.81130625 0.45220587 0.25763863 0.75901389]


In [ ]:
# Matrix for Embeddings
mat = np.random.rand(3 , 3)
print("Matrix: \n" , mat)

Matrix: 
 [[0.89246659 0.17384834 0.03878023]
 [0.8891092  0.51975738 0.32205202]
 [0.96285361 0.11494342 0.17476922]]


In [ ]:
# Basic Operations
print("Mean:" , np.mean(mat))
print("Dot Product:" , np.dot(arr[:3], rand[:3]))

Mean: 0.4542866688875314
Dot Product: 3.6060784949580267


In [ ]:
vec_a = np.random.randn(100)
vec_b = np.random.randn(100)
new_vec = 0.5*vec_a + 0.5*vec_b

In [ ]:
actions = ["move", "turn", "pick"]
prob = [0.4, 0.3, 0.3]
print(np.random.choice(actions, p = prob))

pick


In [ ]:
def cosine(a,b):
  return np.dot(a, b) /(np.linalg.norm(a)*np.linalg.norm(b))